# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n_mNxc74hx_rnIxdFxfltWiSNkzwotJi
"""

# =========================================
# 0. 라이브러리
# =========================================
import streamlit as st
import pandas as pd
import folium
from streamlit_folium import st_folium
import json
import matplotlib.pyplot as plt

# =========================================
# 1. 페이지 설정
# =========================================
st.set_page_config(layout="wide")
st.title("🦠 Disease Dashboard (Chuquisaca)")

# =========================================
# 2. 데이터 로드
# =========================================
@st.cache_data
def load_data():

    df = pd.read_excel(
        "Rociado Chuquisaca 2025.xlsx",
        sheet_name="RESUMEN_2",
        skiprows=8,
        nrows=31
    )

    df.columns = df.columns.str.replace("\n", " ")
    df.columns = df.columns.str.strip()

    df = df.rename(columns={
        "MUNICIPIO": "municipio",
        "EXIST": "viv_exist",
        "ROC": "viv_roc"
    })

    df = df[df["municipio"].notna()]
    df = df[~df["municipio"].str.contains("TOTAL", na=False)]

    df["coverage"] = df["viv_roc"] / df["viv_exist"]

    # 질병 데이터
    df["chagas"] = df["coverage"]
    df["dengue"] = df["coverage"] * 0.8
    df["malaria"] = df["coverage"] * 0.5

    # GeoJSON 로드
    with open("gadm41_BOL_3.json") as f:
        geojson_data = json.load(f)

    return df, geojson_data

df, geojson_data = load_data()

# =========================================
# 3. 사이드바
# =========================================
st.sidebar.header("⚙️ 설정")

disease = st.sidebar.radio(
    "질병 선택",
    ["chagas", "dengue", "malaria"]
)

threshold = st.sidebar.slider(
    "위험 기준",
    0.0, 1.0, 0.2
)

# =========================================
# 4. KPI
# =========================================
avg_cov = df[disease].mean()
total_roc = df["viv_roc"].sum()
risk_count = (df[disease] < threshold).sum()

col1, col2, col3 = st.columns(3)

col1.metric("📊 평균 커버리지", f"{avg_cov:.2%}")
col2.metric("🏠 총 방역", f"{int(total_roc):,}")
col3.metric("⚠️ 위험지역", int(risk_count))

# =========================================
# 5. 데이터 매칭 함수 (핵심)
# =========================================
def get_value(feature):
    name = feature["properties"]["NAME_3"]

    row = df[df["municipio"].str.upper() == name.upper()]

    if len(row) == 0:
        return None

    return float(row[disease].values[0])

# =========================================
# 6. TOP5
# =========================================
top5 = df.nlargest(5, disease)["municipio"].str.upper().tolist()

# =========================================
# 7. 스타일 함수
# =========================================
def style_function(feature):

    value = get_value(feature)
    name = feature["properties"]["NAME_3"].upper()

    if value is None:
        return {"fillColor": "gray", "color": "black", "weight": 1}

    if value < threshold:
        return {"fillColor": "red", "color": "black", "weight": 2}

    if name in top5:
        return {"fillColor": "blue", "color": "black", "weight": 3}

    return {
        "fillColor": "green" if value < 0.3 else "yellow" if value < 0.6 else "red",
        "color": "black",
        "weight": 1,
        "fillOpacity": 0.7
    }

# =========================================
# 8. 지도
# =========================================
st.subheader("🗺️ 지도")

m = folium.Map(location=[-19, -65], zoom_start=8)

folium.GeoJson(
    geojson_data,
    style_function=style_function,
    tooltip=folium.GeoJsonTooltip(
        fields=["NAME_3"],
        aliases=["지역"]
    )
).add_to(m)

map_data = st_folium(m, width=900, height=500)

# =========================================
# 9. 클릭 상세 패널
# =========================================
st.subheader("📍 지역 상세")

selected = None

if map_data and map_data.get("last_active_drawing"):
    selected = map_data["last_active_drawing"]["properties"]["NAME_3"]

if selected:
    row = df[df["municipio"].str.upper() == selected.upper()]

    if len(row) > 0:
        row = row.iloc[0]

        colA, colB = st.columns(2)

        with colA:
            st.markdown(f"### {selected}")
            st.write(f"Coverage: {row[disease]:.2%}")
            st.write(f"방역: {row['viv_roc']}")
            st.write(f"전체: {row['viv_exist']}")

        with colB:
            fig, ax = plt.subplots()
            ax.bar(
                ["Chagas", "Dengue", "Malaria"],
                [row["chagas"], row["dengue"], row["malaria"]]
            )
            st.pyplot(fig)

else:
    st.info("지도에서 지역 클릭")

# =========================================
# 10. TOP5 그래프
# =========================================
st.subheader("📊 TOP 5")

top_df = df.nlargest(5, disease)

fig, ax = plt.subplots()
ax.bar(top_df["municipio"], top_df[disease])
st.pyplot(fig)